### ISSUE TITLE
cannot install server

### ISSUE THREAD

**Issue by laf83** [arduosoft/HubLink#8]
Hi,
i tried to install server (localhost for development), copied in wwwroot dir,  given write access to app_data dir.
Then, started the website for wizard install procedure, all test passed, but install fail.
On log i see: 
2018-05-14 23:26:19.9995 INFO: Application starts  
2018-05-14 23:26:20.0225 INFO: Registering configuration  
2018-05-14 23:26:20.4043 INFO: Hangfire not started up. install wlog first.  

Any help?
thanks!

**Comment by zeppaman** [comment]
Hi @laf83 ,
Did you navigate to install url and followed install process? 

Moreover, wich version are you using? You cloned master branch or download packaged relased?

**Comment by laf83** [comment]
Hi,
i downloaded the package, v1.0.322 BETA. 
I'm using sql server express 2016 as db, so i selected 2012 dialect because 2016 dialect is not available.
If there is something i can do to, just ask.

(Btw, i'm italian too!)

**Comment by zeppaman** [comment]
Hublink seems to work correctly using SQL Express and IIS.

This message come out when you started application, but application is not installed. This happens on first time you startup application, until you navigate /install url and  provide database settings. 

After this application is restarted and should connect to database as usual. 

Instead if you played with web.config directly you must specify 

` <add key="WlogInstalled" value="True" />`

to tell that setup is completed. Database will be generated at application startup.

**Comment by laf83** [comment]
Ok so i found the problem, also the wwwroot folder needs the write permissions, not only the App_Data folder.
Thanks!

**Comment by zeppaman** [comment]
Great!

Please share with us your feedback. It's important to have some help to understand what works and what can be done better. 

Moreover. Hublink is still in beta version and development paused from last release. It may be discontinued in future. Anyway any help with the project is welcome.

In case, as I see you are Italian too, we can keep in touch. You can contact me via linkedin or my personal blog. You can find details on my github profile.
